name: CI

on:
  push:
    branches:
      - releases/*

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: rgmills/pull-request-head-to-base@v0.3.3
      with:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        BASE_BRANCH: 'master'
        HEAD_BRANCH: 'releases/v0.3.3'
